<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Connection Ip' => 'IP de conexión',
    'Created Date' => 'Fecha de Creación',
    'Updated Date' => 'Fecha de Actualización',
    'State' => 'Estado',
    'Enable' => 'Activo',
    'Fk Id Token Type' => 'ID Tipo de token',
    'Fk Id User' => 'ID de Usuario',
    'Service ID' => 'ID de Servicio',
    'User ID' => 'ID de Usuario',
    'Expert ID' => 'ID de Experto',
    'Coupon ID' => 'ID de Cupón',
    'ID' => 'ID',
    'Token' => 'Token',
    'Comment' => 'Comentario',
    'Date' => 'Fecha',
    'Address' => 'Dirección',
    'Time' => 'Hora',
    'Lat' => 'Latitud',
    'Lng' => 'Longitud',
    'Name' => 'Nombre',
    'Description' => 'Descripción',
    'Teams' => 'Grupos',
    'Team' => 'Grupo',
    'Update' => 'Actualizar',
    'Delete' => 'Eliminar',
    'Update Team: ' => 'Actualizar Grupo: ',
    'Are you sure you want to delete this item?' => '¿Estas seguro de eliminar este elemento?',
    'Create Team' => 'Nuevo Grupo',
    'Create' => 'Crear',
    'Users' => 'Usuarios',
    'User' => 'Usuario',
    'Administration' => 'Administración',
    'Code' => 'Código',
    'Used' => 'Usado',
    'Quantity' => 'Límite de cupones',
    'Discount' => 'Descuento',
    'Due Date' => 'Fecha de vencimiento',
    'Coupons' => 'Cupones',
    'Coupon' => 'Cupón',
    'New Coupon' => 'Nuevo Cupón',
    'Amount' => 'Monto',
    'Type Coupon ID' => 'Cupón Asignado a'
];
